import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../firebase_options.dart'; // <- generated by flutterfire configure
import 'package:pet_connect_app/theme/app_theme.dart';
import 'dart:async';

class KycPersonalScreen extends StatefulWidget {
  static const routeName = '/kyc-personal';
  const KycPersonalScreen({super.key});

  @override
  State<KycPersonalScreen> createState() => _KycPersonalScreenState();
}

class _KycPersonalScreenState extends State<KycPersonalScreen> {
  final _formKey = GlobalKey<FormState>();
  final _auth = FirebaseAuth.instance;
  String _fullName = '';
  String _phone = '';
  String _otp = '';
  bool _otpSent = false;
  bool _verified = false;
  String _verificationId = '';
  int? _forceResendingToken;
  bool _isSendingOtp = false;
  bool _isVerifying = false;
  bool _isSubmitting = false;
  int _resendCountdown = 0;
  Timer? _resendTimer;

  @override
  void initState() {
    super.initState();
    _initFirebase();
  }

  @override
  void dispose() {
    _resendTimer?.cancel();
    super.dispose();
  }

  Future<void> _initFirebase() async {
    try {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    } catch (e) {
      // ignore if already initialized
    }
  }

  void _startResendTimer() {
    setState(() => _resendCountdown = 30);
    _resendTimer?.cancel();
    _resendTimer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (mounted) {
        setState(() {
          if (_resendCountdown > 0) {
            _resendCountdown--;
          } else {
            _resendTimer?.cancel();
          }
        });
      }
    });
  }

  Future<void> _sendOtp({bool isResend = false}) async {
    FocusScope.of(context).unfocus();
    if (!isResend) {
      if (!_formKey.currentState!.validate()) return;
      _formKey.currentState!.save();
    }

    setState(() => _isSendingOtp = true);
    
    String formattedPhone = _phone.trim();
    if (!formattedPhone.startsWith('+')) {
      formattedPhone = '+91$formattedPhone';
    }
    debugPrint('Sending OTP to: $formattedPhone (original: $_phone)');
    
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(isResend ? 'Resending OTP...' : 'Sending OTP...')),
    );

    await _auth.verifyPhoneNumber(
      phoneNumber: formattedPhone,
      forceResendingToken: isResend ? _forceResendingToken : null,
      verificationCompleted: (PhoneAuthCredential credential) async {
        debugPrint('Phone auto-verified');
        await _auth.signInWithCredential(credential);
        if (mounted) {
          setState(() => _verified = true);
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Phone auto-verified ✅')),
          );
        }
      },
      verificationFailed: (FirebaseAuthException e) {
        debugPrint('Firebase verification failed: ${e.code} - ${e.message}');
        if (mounted) {
          setState(() => _isSendingOtp = false);
          ScaffoldMessenger.of(context)
              .showSnackBar(SnackBar(content: Text('Verification failed: ${e.message}')));
        }
      },
      codeSent: (String verificationId, int? resendToken) {
        debugPrint('OTP sent successfully. Verification ID: $verificationId');
        if (mounted) {
          setState(() {
            _otpSent = true;
            _verificationId = verificationId;
            _forceResendingToken = resendToken;
            _isSendingOtp = false;
          });
          _startResendTimer();

          if (!isResend) {
            showDialog(
              context: context,
              builder: (ctx) => AlertDialog(
                title: const Text("OTP Sent"),
                content: Text("An OTP has been sent to $formattedPhone."),
                actions: [
                  TextButton(
                    onPressed: () => Navigator.of(ctx).pop(),
                    child: const Text("OK"),
                  ),
                ],
              ),
            );
          }
        }
      },
      codeAutoRetrievalTimeout: (String verificationId) {
        debugPrint('Code auto-retrieval timeout. Verification ID: $verificationId');
        if (mounted) {
          setState(() {
            _verificationId = verificationId;
            _isSendingOtp = false;
          });
        }
      },
      timeout: const Duration(seconds: 60),
    ).catchError((e) {
      debugPrint('Error sending OTP: $e');
      if (mounted) {
        setState(() => _isSendingOtp = false);
        ScaffoldMessenger.of(context)
            .showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    });
  }

  Future<void> _verifyOtp() async {
    FocusScope.of(context).unfocus();
    try {
      setState(() => _isVerifying = true);
      final credential = PhoneAuthProvider.credential(
        verificationId: _verificationId,
        smsCode: _otp.trim(),
      );

      await _auth.signInWithCredential(credential);
      if (mounted) {
        setState(() {
          _verified = true;
          _isVerifying = false;
        });
        _resendTimer?.cancel();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text("Phone number verified ✅")),
        );
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isVerifying = false);
        ScaffoldMessenger.of(context)
            .showSnackBar(const SnackBar(content: Text("Invalid OTP ❌")));
      }
    }
  }

  Future<void> _submitKyc() async {
    if (!_formKey.currentState!.validate()) return;
    _formKey.currentState!.save();
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return;

    setState(() => _isSubmitting = true);

    try {
      await Supabase.instance.client.from('kyc_personal').insert({
        'user_id': user.id,
        'full_name': _fullName.trim(),
        'phone': _phone.trim(),
        'is_otp_verified': _verified,
        'status': _verified ? 'pending' : 'unverified',
      });

      showDialog(
        context: context,
        builder: (ctx) => AlertDialog(
          title: const Text("Verification Complete"),
          content: const Text(
              "Your KYC details have been sent for review. An admin will approve them soon. You will be notified when verification completes."),
          actions: [
            TextButton(
                onPressed: () {
                  Navigator.of(ctx).pop();
                  Navigator.pushReplacementNamed(context, '/kyc-pending');
                },
                child: const Text("OK"))
          ],
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFFCF9DF),
      appBar: AppBar(
        title: Text(
          "Level 2: Personal Verification",
          style: GoogleFonts.poppins(fontWeight: FontWeight.w600),
        ),
        backgroundColor: Colors.transparent,
        elevation: 1,
        foregroundColor: AppColors.textDark,
      ),
      body: Padding(
        padding: const EdgeInsets.all(18),
        child: Form(
          key: _formKey,
          child: ListView(
            children: [
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(12),
                  boxShadow: [
                    BoxShadow(
                      color: Colors.black.withOpacity(0.04),
                      blurRadius: 8,
                      offset: const Offset(0, 3),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('Personal Information', style: GoogleFonts.poppins(fontSize: 16, fontWeight: FontWeight.w600)),
                    const SizedBox(height: 8),
                    Text('Enter your full legal name and a phone number we can verify via OTP.', style: GoogleFonts.poppins(fontSize: 12, color: Colors.grey[700])),
                  ],
                ),
              ),
              const SizedBox(height: 20),
              TextFormField(
                decoration: InputDecoration(
                  labelText: "Full Name",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[50],
                ),
                readOnly: _otpSent,
                validator: (v) => v == null || v.isEmpty ? "Enter your name" : null,
                onSaved: (v) => _fullName = v!,
              ),
              const SizedBox(height: 16),
              TextFormField(
                decoration: InputDecoration(
                  labelText: "Phone Number",
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  filled: true,
                  fillColor: Colors.grey[50],
                ),
                readOnly: _otpSent,
                keyboardType: TextInputType.phone,
                validator: (v) {
                  if (v == null || v.isEmpty) return "Enter your phone number";
                  return null;
                },
                onSaved: (v) => _phone = v!,
              ),
              const SizedBox(height: 16),
              if (!_otpSent)
                SizedBox(
                  width: double.infinity,
                  height: 48,
                  child: ElevatedButton(
                    onPressed: _isSendingOtp ? null : () => _sendOtp(),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.black,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: _isSendingOtp ? const CircularProgressIndicator(color: Colors.white) : const Text('Send OTP'),
                  ),
                )
              else ...[
                TextFormField(
                  decoration: const InputDecoration(
                    labelText: "Enter OTP",
                    border: OutlineInputBorder(),
                  ),
                  onChanged: (v) => _otp = v,
                  keyboardType: TextInputType.number,
                ),
                const SizedBox(height: 12),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    if (_resendCountdown > 0)
                      Text('Resend in $_resendCountdown s', style: TextStyle(color: Colors.grey[600])),
                    TextButton(
                      onPressed: _resendCountdown > 0 ? null : () => _sendOtp(isResend: true),
                      child: const Text('Resend OTP'),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                SizedBox(
                  width: double.infinity,
                  height: 48,
                  child: ElevatedButton(
                    onPressed: _isVerifying ? null : _verifyOtp,
                    style: ElevatedButton.styleFrom(
                      backgroundColor: _verified ? Colors.green : Colors.black,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                    ),
                    child: _isVerifying
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2),
                          )
                        : Text(_verified ? 'Verified ✓' : 'Verify OTP'),
                  ),
                ),
              ],
              const SizedBox(height: 24),
              SizedBox(
                height: 52,
                child: ElevatedButton(
                  onPressed: _isSubmitting || !_verified ? null : _submitKyc,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.black,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  ),
                  child: _isSubmitting ? const CircularProgressIndicator(color: Colors.white) : const Text('Submit Verification'),
                ),
              ),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }
}
