// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwXrauuofvuuq_HXQS5QVyazFPf7mdiE',
    appId: '1:543358006471:web:3fb08ee6a2240d20edbae2',
    messagingSenderId: '543358006471',
    projectId: 'pet-connect-7c145',
    authDomain: 'pet-connect-7c145.firebaseapp.com',
    databaseURL: 'https://pet-connect-7c145-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-7c145.firebasestorage.app',
    measurementId: 'G-D5XKMGRGR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_780NTsg_BB35rixLQhG_ebu81M6bHM',
    appId: '1:543358006471:android:531c1987a1d01d91edbae2',
    messagingSenderId: '543358006471',
    projectId: 'pet-connect-7c145',
    databaseURL: 'https://pet-connect-7c145-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-7c145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGY429rhrRyapppvPHxuE2Uond6eh0AJA',
    appId: '1:543358006471:ios:7dc9817f2970eb38edbae2',
    messagingSenderId: '543358006471',
    projectId: 'pet-connect-7c145',
    databaseURL: 'https://pet-connect-7c145-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-7c145.firebasestorage.app',
    iosClientId: '543358006471-n8m72rnc26nofvl9rh8s2jss5feelicq.apps.googleusercontent.com',
    iosBundleId: 'com.example.petConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGY429rhrRyapppvPHxuE2Uond6eh0AJA',
    appId: '1:543358006471:ios:7dc9817f2970eb38edbae2',
    messagingSenderId: '543358006471',
    projectId: 'pet-connect-7c145',
    databaseURL: 'https://pet-connect-7c145-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-7c145.firebasestorage.app',
    iosClientId: '543358006471-n8m72rnc26nofvl9rh8s2jss5feelicq.apps.googleusercontent.com',
    iosBundleId: 'com.example.petConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPwXrauuofvuuq_HXQS5QVyazFPf7mdiE',
    appId: '1:543358006471:web:6f6c266798b75b7bedbae2',
    messagingSenderId: '543358006471',
    projectId: 'pet-connect-7c145',
    authDomain: 'pet-connect-7c145.firebaseapp.com',
    databaseURL: 'https://pet-connect-7c145-default-rtdb.firebaseio.com',
    storageBucket: 'pet-connect-7c145.firebasestorage.app',
    measurementId: 'G-XXW73W8X3T',
  );

}