// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJHqgPxiiQ5fz6mx86It_t5wVGlfAQszg',
    appId: '1:978698245676:web:17ba93c8ccfdbd695e6389',
    messagingSenderId: '978698245676',
    projectId: 'patconnect-4251b',
    authDomain: 'patconnect-4251b.firebaseapp.com',
    storageBucket: 'patconnect-4251b.firebasestorage.app',
    measurementId: 'G-E1WVRQ0F5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGOS_ONge_sSKOPSuvC8t7NsvoUCLepF0',
    appId: '1:978698245676:android:1dddf9c1ebc64d0f5e6389',
    messagingSenderId: '978698245676',
    projectId: 'patconnect-4251b',
    storageBucket: 'patconnect-4251b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7XjNLfaRnzG5DAurpbr3WSw8NHoIOWj4',
    appId: '1:978698245676:ios:90c899829071bcc05e6389',
    messagingSenderId: '978698245676',
    projectId: 'patconnect-4251b',
    storageBucket: 'patconnect-4251b.firebasestorage.app',
    iosBundleId: 'com.example.petConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7XjNLfaRnzG5DAurpbr3WSw8NHoIOWj4',
    appId: '1:978698245676:ios:90c899829071bcc05e6389',
    messagingSenderId: '978698245676',
    projectId: 'patconnect-4251b',
    storageBucket: 'patconnect-4251b.firebasestorage.app',
    iosBundleId: 'com.example.petConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJHqgPxiiQ5fz6mx86It_t5wVGlfAQszg',
    appId: '1:978698245676:web:cff81b07604221085e6389',
    messagingSenderId: '978698245676',
    projectId: 'patconnect-4251b',
    authDomain: 'patconnect-4251b.firebaseapp.com',
    storageBucket: 'patconnect-4251b.firebasestorage.app',
    measurementId: 'G-FGJR6G2CLV',
  );
}
